spring:
  datasource:
    username: root
    password: 940901!
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  type-aliases-package: com.comtruetech.managementprogram
  mapper-locations: mapper/**/*.xml

# swagger / http://localhost:8080/swagger
springdoc:
  swagger-ui:
    path: /swagger.html